[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
exclude = [".?venv*"]

[tool.pylint.master]
ignore-patterns = [".?venv*"]
jobs = 0
disable = [
  'invalid-name',
  'too-few-public-methods',
  'too-many-arguments',
  'too-many-instance-attributes',
  'import-error',
  'too-few-public-methods',
  'fixme',
]

[tool.pylint.similarities]
ignore-imports = true

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.idea
    | \.?venv.*
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
src_paths = ["src"]

[tool.coverage.run]
branch = false
omit = [
  '*tests*',
  '*venv*',
  '*/__init__.py'
]

[tool.coverage.report]
exclude_lines = [
  'pragma: no cover',
  'def __repr__',
  'if self\.debug',
  'raise AssertionError',
  'raise NotImplementedError',
  'if TYPE_CHECKING:',
  'if 0:',
  'if __name__ == .__main__.:'
]
ignore_errors = true

[tool.coverage.html]
directory = 'htmlcov'
